### ISSUE TITLE
Translating text to HTML characters..

### ISSUE THREAD

**Issue by Chaprnks** [bhaskardabhi/atom-translator#1]
Example:
![1](https://user-images.githubusercontent.com/6340970/38439268-092d436c-39ab-11e8-8a57-1c51654fe035.png)

translates to:
![2](https://user-images.githubusercontent.com/6340970/38439272-0b44bc16-39ab-11e8-98b6-3864c08f57f1.png)

**Comment by bhaskardabhi** [comment]
@Chaprnks can u give me the text that u trying to convert? Also let me know in which language u want to convert it to?

**Comment by MairwunNx** [comment]
I have the same problem, I try to translate any Russian text into English (en) tried and (us), did not help, the same symbols, fix it! Очевидно же, что парень сверху переводит с русского на другой язык.

**Comment by Chaprnks** [comment]
@bhaskardabhi It's any Cyrillic based text that I am trying to translate into English. I believe the text gets translated.. but it outputs in HTML code format, not ASCII/plaintext.

**Comment by bhaskardabhi** [comment]
@MairwunNx its fixed in v0.2.2 release.

**Comment by bhaskardabhi** [comment]
@Chaprnks can u give me the text?
