### ISSUE TITLE
Google API v2 blocked

### ISSUE THREAD

**Issue by alerque** [bhaskardabhi/atom-translator#3]
I have added an API key, setup a billing account, and enabled access to the API. I still get a message about the API  being blocked, specifically mentioning v2. I think whatever API endpoint this plugin uses must me depricated.

**Comment by bhaskardabhi-oviyum** [comment]
@alerque Sure will look into it.

**Comment by bhaskardabhi** [comment]
Hi @alerque  We are using v2 only. I am not facing any issue. 

I went to https://console.cloud.google.com/apis/credentials & generated API key

![Google Api key](https://i.imgur.com/N2bn9WSl.png). Translation worked.
